<?php
  $this->headTitle()->setSeparator(' - ');
  $this->headTitle('GoalFace.com','PREPEND');

  echo $this->doctype(); ?>


<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> 
<html class="no-js" lang="en"> 
<!--<![endif]-->
<head>
  <?php $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8'); ?>
  <!-- Set the viewport width to device width for mobile -->
  <?php $this->headMeta()->appendName('viewport','width=device-width'); ?>
  
  <!-- Included CSS Files (Compressed) -->
  <?php $this->headLink()->appendStylesheet('/styles/layouts.css')
                         ->appendStylesheet('/styles/goalface.css')
                         ->appendStylesheet('/styles/menu.css'); ?>
 
  <?php $this->headScript()->appendFile('/scripts/jquery-1.6.4.min.js')
                            ->appendFile('/scripts/menu.js'); ?>

  <?php echo $this->headMeta(); ?>
  
  <?php echo $this->headTitle(); ?>

  <?php echo $this->headLink(); ?>
  
  <?php echo $this->headScript(); ?>

  <!-- IE Fix for HTML5 Tags -->
  <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

</head>
<body class="home">
  <div><!-- container -->
    <div id="wrapper">
    
      <!-- Top header -->
      <?php //echo $this->render('_header.phtml') ?>
     
      <!-- Main Content -->
      <?php echo $this->layout()->content; ?>
     
      <!-- Footer -->
      <?php echo $this->render('_footer.phtml') ?>
   
    </div>
   
   <!-- container --> 
    
    <!-- Included JS Files (Uncompressed) -->
    <!--
    
    <script src="/javascripts/modernizr.foundation.js"></script>
    
    <script src="/javascripts/jquery.js"></script>
    
    <script src="/javascripts/jquery.foundation.mediaQueryToggle.js"></script>
    
    <script src="/javascripts/jquery.foundation.reveal.js"></script>
    
    <script src="/javascripts/jquery.foundation.orbit.js"></script>
    
    <script src="/javascripts/jquery.foundation.navigation.js"></script>
    
    <script src="/javascripts/jquery.foundation.buttons.js"></script>
    
    <script src="/javascripts/jquery.foundation.tabs.js"></script>
    
    <script src="/javascripts/jquery.foundation.forms.js"></script>
    
    <script src="/javascripts/jquery.foundation.tooltips.js"></script>
    
    <script src="/javascripts/jquery.foundation.accordion.js"></script>
    
    <script src="/javascripts/jquery.placeholder.js"></script>
    
    <script src="/javascripts/jquery.foundation.alerts.js"></script>
    
    -->
  </div>
</body>
</html>
